url: https://strelisce-novomesto.si
baseurl: ""

# Site settings
title: Strelišče Rojal
email: sd@rojal.si
description: "Notranje strelišče v Novem mestu."

workinghours:
  - title: "Sreda"
    hours: "18:00 - 20:00"

#  - title: "Nedelja"
#    hours: "9:00 - 12:00"

address:
  title: SD Rojal
  street: Ilke Vaštetove 13
  city: 8000 Novo mesto

googleMaps: https://g.page/sdrojal?share

files:
  statut: https://docs.google.com/document/d/1FbaxWk6PN-HT9nPf7dMqIgNQxfZNABIWhcQfve2mKfE/edit?usp=sharing
  pravilnikClanstvu: https://docs.google.com/document/d/1-0chkKzRm4ljUquVjfW9smeIA7SL3FysxzL_53PNudg/edit?usp=sharing
  prijavnicaizpit: /img/files/SK Rojal Prijava k preizkusu znanja o ravnanju z orozjem.pdf
  prijavnicatecaj: /img/files/SK Rojal Prijava na usposabljanje - tecaj.pdf
  elprijavnicatecaj: https://forms.gle/DLMduFdDEtguGvj58

pricelist:
  - title: "Letno redno članstvo v SD Rojal"
    subtitle: "Neomejena uporaba strelišča"
    price: "100 EUR"

  - title: "Letno članstvo v SD Rojal za neaktivne člane"
    subtitle: "Uporaba klubskega strelišča ni všteta"
    price: "40 EUR"

  - title: "Pristopnina za nove letne člane"
    price: "20 EUR"

  - title: "Standard pištolska tarča 50x50"
    price: "0,60 EUR / kom"

  - title: "Uporaba strelišča za nečlana"
    price: "10 EUR / h"

  - title: "Prisotnost inštruktorja oz. odgovorne osebe (do 4 osebe)"
    subtitle: "Potrebno samo v primeru, če strelec nima orožne listine"
    price: "15 EUR"

  - title: "Prisotnost inštruktorja oz. odgovorne osebe (5 oseb ali več)"
    subtitle: "Potrebno samo v primeru, če strelec nima orožne listine"
    price: "35 EUR"

  - title: "Izposoja orožja"
    price: "6 EUR"

pricelistammo:
  - title: ".22 L.R."
    price: "0,14 EUR"

  - title: "9x19"
    price: "0,35 EUR"

  - title: ".38 Special"
    price: "0,45 EUR"

  - title: ".357 Magnum"
    price: "0,60 EUR"

  - title: "Šibreno strelivo"
    price: "1,00 EUR"

pricelisttecaj:
  - title: "Usposabljanje in preizkus znanja o ravnanju z orožjem"
    price: "200,00 EUR"

  - title: "Usposabljanje, teoretični del in potrdilo"
    subtitle: "npr. v primeru dedovanja"
    price: "150,00 EUR"

  - title: "Posebni del preizkusa znanja o ravnanju z orožjem (Kratkocevno orožje)"
    price: "40,00 EUR"

  - title: "Posebni del preizkusa znanja o ravnanju z orožjem (Dolgocevno orožje)"
    price: "50,00 EUR"

  - title: "Ponovno opravljanje izpita, teorija + praksa"
    price: "90,00 EUR"

  - title: "Ponovno opravljanje izpita, praktični del"
    price: "60,00 EUR"

  - title: "Izdaja novega ali dodatnega potrdila"
    price: "20,00 EUR"

# orozje:
#   - title: "Norinco NP26"
#     tip: "Polavtomatska pištola"
#     cal: "9x19"
#     desc: "opis... alalala"
#     img: "http://www.firearmstraining.ca/images/np28leftsmall.jpg"

# pricelistfootnote:
#   - "* Zaposlenim na MNZ, Mors ter Pravosodju, se prizna popust na enodnevno članstvo v višini 2 eur."
#   - "Pogoj za uporabo strelišča je veljavna orožna listina ter posest lastnega orožja."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/sdrojal

  - title: envelope
    url: mailto:sd@rojal.si

  - title: map-marker
    url: https://g.page/sdrojal?share

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: compact # possible values: nested expanded compact compressed
