url: https://strelisce-novomesto.si
baseurl: ""

# Site settings
title: Strelišče Rojal
email: sd@rojal.si
description: "Notranje strelišče v Novem mestu."

workinghours:
  - title: "Sreda"
    hours: "18:00 - 20:00"

#  - title: "Nedelja"
#    hours: "9:00 - 12:00"

address:
  title: SD Rojal
  street: Ilke Vaštetove 13
  city: 8000 Novo mesto

googleMaps: https://g.page/sdrojal?share

pricelist:
  - title: "Enodnevno članstvo v SD Rojal *"
    subtitle: "Omejena uporaba strelišča 1 ura na dan"
    price: "10 EUR"

  - title: "Letno članstvo v SD Rojal *"
    subtitle: "(Neomejena uporaba strelišča)"
    price: "100 EUR"

  - title: "Standard pištolska tarča 50x50"
    price: "0,60 EUR / kom"

pricelistfootnote:
  - "* Zaposlenim na MNZ, Mors ter Pravosodju, se prizna popust na enodnevno članstvo v višini 2 eur."
  - "Pogoj za uporabo strelišča je veljavna orožna listina ter posest lastnega orožja."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/sdrojal

  - title: envelope
    url: mailto:sd@rojal.si

  - title: map-marker
    url: https://g.page/sdrojal?share

# Build settings
markdown: kramdown
permalink: pretty
