url: https://strelisce-novomesto.si
baseurl: ""

# Site settings
title: Strelišče Rojal
email: sd@rojal.si
description: "Notranje strelišče v Novem mestu."

workinghours:
  - title: "Sreda"
    hours: "18:00 - 20:00"

#  - title: "Nedelja"
#    hours: "9:00 - 12:00"

address:
  title: SD Rojal
  street: Ilke Vaštetove 13
  city: 8000 Novo mesto

googleMaps: https://g.page/sdrojal?share

files:
  statut: https://docs.google.com/document/d/1FbaxWk6PN-HT9nPf7dMqIgNQxfZNABIWhcQfve2mKfE/edit?usp=sharing
  pravilnikClanstvu: https://docs.google.com/document/d/1-0chkKzRm4ljUquVjfW9smeIA7SL3FysxzL_53PNudg/edit?usp=sharing
  prijavnicaizpit: /img/files/SK Rojal Prijava k preizkusu znanja o ravnanju z orozjem.pdf
  prijavnicatecaj: /img/files/SK Rojal Prijava na usposabljanje - tecaj.pdf
  elprijavnicatecaj: https://forms.gle/DLMduFdDEtguGvj58
  elprijavnicaizpit: https://forms.gle/22jSK7FVACMrhHLNA

pricelist:
  - title: "Letno redno članstvo v SD Rojal"
    subtitle: "Neomejena uporaba strelišča (50 % popust od drugega leta naprej)"
    price: "200 EUR"

  # - title: "Letno članstvo v SD Rojal za neaktivne člane"
  #   subtitle: "Uporaba klubskega strelišča ni všteta"
  #   price: "50 EUR"

  - title: "Standard pištolska tarča 50x50"
    price: "0,60 EUR / kom"

  - title: "Uporaba strelišča za nečlane"
    price: "20 EUR / h"

  - title: "Prisotnost inštruktorja oz. odgovorne osebe (do 3 osebe)"
    subtitle: "Potrebno samo v primeru, če strelec nima orožne listine ali ko gre za skupine"
    price: "15 EUR"

  - title: "Prisotnost inštruktorja oz. odgovorne osebe (4 oseb ali več)"
    subtitle: "Potrebno samo v primeru, če strelec nima orožne listine ali ko gre za skupine"
    price: "45 EUR"

  - title: "Izposoja orožja"
    price: "6 EUR"

pricelistammo:
  - title: ".22 L.R."
    price: "0,21 EUR"

  - title: "9x19"
    price: "0,38 EUR"

  - title: "9x17 (.380 ACP)"
    price: "0,38 EUR"

  - title: ".38 Special"
    price: "0,55 EUR"

  - title: ".357 Magnum"
    price: "0,60 EUR"

  - title: "Šibreno strelivo"
    price: "1,50 EUR"

pricelisttecaj:
  - title: "Usposabljanje in preizkus znanja (izpit) o ravnanju z orožjem"
    subtitle: "Vsebuje tečaj in izpit"
    price: "290,00 EUR"

  - title: "Usposabljanje, teoretični del in potrdilo"
    subtitle: "npr. v primeru dedovanja"
    price: "200,00 EUR"

  - title: "Preizkus znanja (izpit) o ravnanju z orožjem (teoretični + praktični del)"
    subtitle: "Celotni izpit. Za ponavljalce ali kandidate, ki tečaja niso opravljali pri nas."
    price: "100,00 EUR"

  - title: "Ponovno opravljanje izpita, praktični del"
    price: "70,00 EUR"

  - title: "Posebni del preizkusa znanja o ravnanju z orožjem (Kratkocevno orožje)"
    price: "40,00 EUR"

  - title: "Posebni del preizkusa znanja o ravnanju z orožjem (Dolgocevno orožje)"
    price: "50,00 EUR"

  - title: "Izdaja novega ali dodatnega potrdila"
    price: "20,00 EUR"

# orozje:
#   gsg1911:
#     title: "GSG 1911"
#     tip: "Polavtomatska pištola"
#     cal: ".22 LR"
#     desc: ""
#     img: "gsg1911.jpg"
#   toz35:
#     title: "TOZ 35"
#     tip: "Pištola"
#     cal: ".22 LR"
#     desc: ""
#     img: "TOZ-35.jpeg"
#   cz92:
#     title: "CZ 92"
#     tip: "Polavtomatska pištola"
#     cal: ".25 ACP"
#     desc: ""
#     img: "cz92.jpg"
#   ppn:
#     title: "Norinco PPN"
#     tip: "Polavtomatska pištola"
#     cal: ".380 ACP"
#     desc: ""
#     img: "ppn.jpeg"
#   m57:
#     title: "Zastava M57"
#     tip: "Polavtomatska pištola"
#     cal: "7.62x25mm Tokarev"
#     desc: ""
#     img: "m57.jpg"
#   nz85b:
#     title: "Norinco NZ85B"
#     tip: "Polavtomatska pištola"
#     cal: "9x19"
#     desc: ""
#     img: "nz85b.jpeg"
#   tanfmatch:
#     title: "Tanfoglio Wie Match"
#     tip: "Polavtomatska pištola"
#     cal: "9x19"
#     desc: ""
#     img: "tanfmatch.jpg"
#   glock17:
#     title: "Glock 17"
#     tip: "Polavtomatska pištola"
#     cal: "9x19"
#     desc: ""
#     img: "glock17.jpg"
#   delta:
#     title: "Rex Delta X Gen.2"
#     tip: "Polavtomatska pištola"
#     cal: "9x19"
#     desc: ""
#     img: "deltax.jpeg"
#   deltamor:
#     title: "Rex Delta M OR Gen.2"
#     tip: "Polavtomatska pištola"
#     cal: "9x19"
#     desc: ""
#     img: "deltamor.jpeg"
#   zero1:
#     title: "Rex Zero1 Standard"
#     tip: "Polavtomatska pištola"
#     cal: "9x19"
#     desc: ""
#     img: "zero1.jpeg"
#   taurus809c:
#     title: "Taurus 809c"
#     tip: "Polavtomatska pištola"
#     cal: "9x19"
#     desc: ""
#     img: "809c.jpg"
#   taurus605:
#     title: "Taurus 605"
#     tip: "Revolver"
#     cal: ".357 Magnum"
#     desc: ""
#     img: "605.jpg"
#   uberti44:
#     title: "Uberti Single Action Target"
#     tip: "Revolver"
#     cal: ".44 Magnum"
#     desc: ""
#     img: "uberti44.jpg"
#   kralsa001:
#     title: "Kral AV SA-001"
#     tip: "Polavtomatska puška z gladko cevjo"
#     cal: "20 GA"
#     desc: ""
#     img: "sa001.jpeg"
#   uzkontrx:
#     title: "Uzkon TRX"
#     tip: "Repetirna puška z gladko cevjo"
#     cal: "12 GA"
#     desc: ""
#     img: "trx.jpeg"
#   mosin:
#     title: "Mosin Nagant M91/30"
#     tip: "Repetirna puška z risano cevjo"
#     cal: "7.62x54R"
#     desc: ""
#     img: "mosin.jpg"
#   tippmann:
#     title: "Tippmann M4-22 Elite-L 16 M-LOK"
#     tip: "Polavtomatska puška z risano cevjo"
#     cal: ".22 LR"
#     desc: ""
#     img: "tippmann.jpg"
#   glock17roni:
#     title: "Glock 17 Micro Roni"
#     tip: "Polavtomatska pištola"
#     cal: "9x19"
#     desc: ""
#     img: "glock17roni.jpg"
#   oberland9:
#     title: "Oberland PR M9 Heavy Barrel"
#     tip: "Polavtomatska puška z risano cevjo"
#     cal: "9x19"
#     desc: ""
#     img: "oberlandprm9.jpg"
#   oberland223:
#     title: "Oberland OA-15 BL M-LOK M4"
#     tip: "Polavtomatska puška z risano cevjo"
#     cal: ".223 REM"
#     desc: ""
#     img: "oberlandmlmlok.jpg"

# paketi:
#   - title: "Paket Pištola Začetnik"
#     price: 45,00 EUR / oseba
#     guns:
#       gsg1911: "15 nabojev"
#       nz85b: "15 nabojev"

#   - title: "Paket Pištola"
#     price: 50,00 EUR / oseba
#     guns:
#       nz85b: "15 nabojev"
#       delta: "15 nabojev"

#   - title: "Paket Arex Defense 2"
#     price: 60,00 EUR / oseba
#     guns:
#       delta: "15 nabojev"
#       zero1: "15 nabojev"
#       deltamor: "15 nabojev"

#   - title: "Paket Pištola L"
#     price: 60,00 EUR / oseba
#     guns:
#       nz85b: "15 nabojev"
#       tanfmatch: "15 nabojev"
#       delta: "15 nabojev"

#   - title: "Paket Polymer Frame"
#     price: 60,00 EUR / oseba
#     guns:
#       taurus809c: "15 nabojev"
#       delta: "15 nabojev"
#       deltamor: "15 nabojev"

#   - title: "Paket Pištola XL"
#     price: 72,00 EUR / oseba
#     guns:
#       gsg1911: "10 nabojev"
#       nz85b: "10 nabojev"
#       ppn: "10 nabojev"
#       tanfmatch: "10 nabojev"
#       delta: "10 nabojev"

#   - title: "Paket Pištola / Revolver"
#     price: 55,00 EUR / oseba
#     guns:
#       nz85b: "10 nabojev"
#       delta: "10 nabojev"
#       taurus605: "6 nabojev"

#   - title: "Paket Mega"
#     price: 85,00 EUR / oseba
#     guns:
#       nz85b: "10 nabojev"
#       tanfmatch: "10 nabojev"
#       delta: "10 nabojev"
#       taurus605: "6 nabojev"
#       kralsa001: "4 nabojev"
#       mosin: "5 nabojev"

#   - title: "Paket Rifles"
#     price: "100 EUR / oseba"
#     guns:
#       mosin: "5 nabojev"
#       tippmann: "25 nabojev"
#       oberland223: "5 nabojev"
#       oberland9: "25 nabojev"

#   - title: "Paket XXL 200 nabojev / 14 orožij"
#     price: 250,00 EUR / oseba
#     guns:
#       gsg1911: "20 nabojev"
#       ppn: "10 nabojev"
#       nz85b: "20 nabojev"
#       delta: "20 nabojev"
#       deltamor: "20 nabojev"
#       tanfmatch: "20 nabojev"
#       taurus809c: "20 nabojev"
#       zero1: "20 nabojev"
#       taurus605: "6 nabojev"
#       uzkontrx: "4 nabojev"
#       tippmann: "25 nabojev"
#       oberland223: "5 nabojev"
#       oberland9: "25 nabojev"
#       mosin: "5 nabojev"

orozje:
  gsg1911:
    title: "GSG 1911"
    tip: "Polavtomatska pištola"
    cal: ".22 LR"
    desc: ""
    img: "gsg1911.jpg"
  toz35:
    title: "TOZ 35"
    tip: "Pištola"
    cal: ".22 LR"
    desc: ""
    img: "TOZ-35.jpeg"
  cz92:
    title: "CZ 92"
    tip: "Polavtomatska pištola"
    cal: ".25 ACP"
    desc: ""
    img: "cz92.jpg"
  ppn:
    title: "Norinco PPN"
    tip: "Polavtomatska pištola"
    cal: ".380 ACP"
    desc: ""
    img: "ppn.jpeg"
  m57:
    title: "Zastava M57"
    tip: "Polavtomatska pištola"
    cal: "7.62x25mm Tokarev"
    desc: ""
    img: "m57.jpg"
  nz85b:
    title: "Norinco NZ85B"
    tip: "Polavtomatska pištola"
    cal: "9x19"
    desc: ""
    img: "nz85b.jpeg"
  tanfmatch:
    title: "Tanfoglio Wie Match"
    tip: "Polavtomatska pištola"
    cal: "9x19"
    desc: ""
    img: "tanfmatch.jpg"
  glock17:
    title: "Glock 17"
    tip: "Polavtomatska pištola"
    cal: "9x19"
    desc: ""
    img: "glock17.jpg"
  delta:
    title: "Rex Delta X Gen.2"
    tip: "Polavtomatska pištola"
    cal: "9x19"
    desc: ""
    img: "deltax.jpeg"
  deltamor:
    title: "Rex Delta M OR Gen.2"
    tip: "Polavtomatska pištola"
    cal: "9x19"
    desc: ""
    img: "deltamor.jpeg"
  zero1:
    title: "Rex Zero1 Standard"
    tip: "Polavtomatska pištola"
    cal: "9x19"
    desc: ""
    img: "zero1.jpeg"
  taurus809c:
    title: "Taurus 809c"
    tip: "Polavtomatska pištola"
    cal: "9x19"
    desc: ""
    img: "809c.jpg"
  taurus605:
    title: "Taurus 605"
    tip: "Revolver"
    cal: ".357 Magnum"
    desc: ""
    img: "605.jpg"
  uberti44:
    title: "Uberti Single Action Target"
    tip: "Revolver"
    cal: ".44 Magnum"
    desc: ""
    img: "uberti44.jpg"
  kralsa001:
    title: "Kral AV SA-001"
    tip: "Polavtomatska puška z gladko cevjo"
    cal: "20 GA"
    desc: ""
    img: "sa001.jpeg"
  uzkontrx:
    title: "Uzkon TRX"
    tip: "Repetirna puška z gladko cevjo"
    cal: "12 GA"
    desc: ""
    img: "trx.jpeg"
  mosin:
    title: "Mosin Nagant M91/30"
    tip: "Repetirna puška z risano cevjo"
    cal: "7.62x54R"
    desc: ""
    img: "mosin.jpg"
  tippmann:
    title: "Tippmann M4-22 Elite-L 16 M-LOK"
    tip: "Polavtomatska puška z risano cevjo"
    cal: ".22 LR"
    desc: ""
    img: "tippmann.jpg"
  glock17roni:
    title: "Glock 17 Micro Roni"
    tip: "Polavtomatska pištola"
    cal: "9x19"
    desc: ""
    img: "glock17roni.jpg"
  oberland9:
    title: "Oberland PR M9 Heavy Barrel"
    tip: "Polavtomatska puška z risano cevjo"
    cal: "9x19"
    desc: ""
    img: "oberlandprm9.jpg"
  oberland223:
    title: "Oberland OA-15 BL M-LOK M4"
    tip: "Polavtomatska puška z risano cevjo"
    cal: ".223 REM"
    desc: ""
    img: "oberlandmlmlok.jpg"
  taurusTX22:
    title: "Taurus TX 22 Gen2"
    tip: "Polavtomatska pištola"
    cal: ".22 LR"
    desc: ""
    img: "TaurusTX22Gen2.jpeg"
  deserteagle:
    title: "IWI Desert Eagle"
    tip: "Polavtomatska pištola"
    cal: ".50 AE"
    desc: ""
    img: "IWI_feserteagle.jpeg"
  TP9metePRO:
    title: "Canik TP9 Mete SFT Pro"
    tip: "Polavtomatska pištola"
    cal: "9x19"
    desc: ""
    img: "mete-sft-pro.jpeg"
  waltherP01:
    title: "Walther P-01"
    tip: "Polavtomatska pištola"
    cal: "9x19"
    desc: ""
    img: "Walther_P-01.jpeg"
  glock21:
    title: "Glock 21"
    tip: "Polavtomatska pištola"
    cal: ".45 ACP"
    desc: ""
    img: "Glock_21.jpeg"
  smithwesson686:
    title: "Smith Wesson 686 Target Champion"
    tip: "Revolver"
    cal: ".357 Magnum"
    desc: ""
    img: "Smith-and-Wesson-model-627.jpeg"
  uberti454:
    title: "A. Uberti Tornado 454"
    tip: "Revolver"
    cal: ".454 Casull"
    desc: ""
    img: "uberti-454-casull.jpeg"
  smithwesson500:
    title: "Smith Wesson MOD 500"
    tip: "Revolver"
    cal: ".500 SW Magnum"
    desc: ""
    img: "Smith-Wesson-500-S-W-Magnum.jpeg"
  jw20:
    title: "Norinco JW-20"
    tip: "Repetirna puška z risano cevjo"
    cal: ".22 LR"
    desc: ""
    img: "jW-20.jpeg"
  ptac:
    title: "Pallas P-Tac Tactical"
    tip: "Repetirna puška z gladko cevjo"
    cal: "12 GA"
    desc: ""
    img: "pallas_p-tac_home_defence_12-76.jpeg"
  skorpion:
    title: "CZ Skorpion"
    tip: "Polavtomatska pištola"
    cal: "7,65 Browning"
    desc: ""
    img: "cz_scorpion.jpeg"
  m70:
    title: "CZ M70"
    tip: "Polavtomatska pištola"
    cal: "7,65 Browning"
    desc: ""
    img: "CZ_70.jpeg"

paketi:
  - title: "Paket Pištola - osnovni"
    price: 45,00 EUR / oseba
    guns:
      taurusTX22: "20 nabojev"
      nz85b: "15 nabojev"

  - title: "Paket Pištola L"
    price: 60,00 EUR / oseba
    guns:
      zero1: "15 nabojev"
      delta: "15 nabojev"
      TP9metePRO: "15 nabojev"

  - title: "Paket Pištola XL"
    price: 75,00 EUR / oseba
    guns:
      taurusTX22: "20 nabojev"
      nz85b: "10 nabojev"
      ppn: "10 nabojev"
      delta: "10 nabojev"
      TP9metePRO: "10 nabojev"

  - title: "Paket Pištola XXL"
    price: 90,00 EUR / oseba
    guns:
      taurusTX22: "20 nabojev"
      tanfmatch: "10 nabojev"
      waltherP01: "10 nabojev"
      delta: "10 nabojev"
      TP9metePRO: "10 nabojev"
      glock21: "10 nabojev"
      deserteagle: "5 nabojev"
  
  - title: "Paket Pištola / Revolver"
    price: 60,00 EUR / oseba
    guns:
      taurusTX22: "20 nabojev"
      delta: "10 nabojev"
      smithwesson686: "6 nabojev"

  - title: "Paket Pištola / Revolver L"
    price: 75,00 EUR / oseba
    guns:
      taurusTX22: "20 nabojev"
      nz85b: "10 nabojev"
      delta: "10 nabojev"
      smithwesson686: "6 nabojev"
      uberti44: "2 nabojev"

  - title: "Paket Pištola / Revolver XL"
    price: 90,00 EUR / oseba
    guns:
      taurusTX22: "20 nabojev"
      nz85b: "10 nabojev"
      delta: "10 nabojev"
      TP9metePRO: "10 nabojev"
      smithwesson686: "6 nabojev"
      uberti44: "5 nabojev"
      uberti454: "2 naboja"

  - title: "Paket Rifles"
    price: 100,00 EUR / oseba
    guns:
      mosin: "5 nabojev"
      tippmann: "25 nabojev"
      oberland223: "5 nabojev"
      oberland9: "20 nabojev"

  - title: "Paket Rifles XL"
    price: 125,00 EUR / oseba
    guns:
      jw20: "20 nabojev"
      mosin: "5 nabojev"
      tippmann: "25 nabojev"
      oberland223: "5 nabojev"
      oberland9: "20 nabojev"
      ptac: "4 naboji"

  - title: "Paket Combo"
    price: 85 EUR / oseba
    guns:
      taurusTX22: "20 nabojev"
      delta: "10 nabojev"
      smithwesson686: "6 nabojev"
      ptac: "4 naboji"
      mosin: "5 nabojev"

  - title: "Paket Combo L"
    price: 100,00 EUR / oseba
    guns:
      taurusTX22: "20 nabojev"
      nz85b: "10 nabojev"
      delta: "10 nabojev"
      smithwesson686: "6 nabojev"
      tippmann: "25 nabojev"
      ptac: "4 naboji"
      mosin: "5 nabojev"

  - title: "Paket Combo XL"
    price: 150,00 EUR / oseba
    guns:
      taurusTX22: "20 nabojev"
      nz85b: "10 nabojev"
      delta: "10 nabojev"
      smithwesson686: "6 nabojev"
      skorpion: "5 nabojev"
      tippmann: "25 nabojev"
      oberland9: "20 nabojev"
      oberland223: "5 nabojev"
      ptac: "4 naboji"
      mosin: "5 nabojev"

  - title: "Paket Combo XXL 200 nabojev / 15 orožij"
    price: 250,00 EUR / oseba
    guns:
      taurusTX22: "20 nabojev"
      ppn: "10 nabojev"
      m57: "8 nabojev"
      nz85b: "20 nabojev"
      delta: "20 nabojev"
      zero1: "20 nabojev"
      TP9metePRO: "20 nabojev"
      smith&esson686: "6 nabojev"
      deserteagle: "7 nabojev"
      skorpion: "10 nabojev"
      tippmann: "25 nabojev"
      oberland9: "20 nabojev"
      oberland223: "5 nabojev"
      ptac: "4 naboji"
      mosin: "5 nabojev"

  - title: "Paket Super Combo Delux 135 nabojev/ 13 kalibrov/ 15 nabojev"
    price: 275,00 EUR / oseba
    guns:
      m57: "8 nabojev"
      waltherP01: "8 nabojev"
      glock17: "20 nabojev"
      glock21: "10 nabojev"
      deserteagle: "5 nabojev"
      smithwesson686: "6 nabojev"
      uberti44: "5 nabojev"
      uberti454: "2 naboja"
      smithwesson500: "2 naboja"
      skorpion: "10 nabojev"
      tippmann: "25 nabojev"
      oberland9: "20 nabojev"
      oberland223: "5 nabojev"
      ptac: "4 naboji"
      mosin: "5 nabojev"

  - title: "Paket &quot; Big Boy &quot;	 veliki kalibri / Do you feel lucky, punk?!"
    price: 125,00 EUR / oseba
    guns:
      glock21: "10 nabojev"
      deserteagle: "5 nabojev"
      smithwesson686: "6 nabojev"
      uberti44: "5 nabojev"
      uberti454: "2 naboja"
      smithwesson500: "2 naboja"

# pricelistfootnote:
#   - "* Zaposlenim na MNZ, Mors ter Pravosodju, se prizna popust na enodnevno članstvo v višini 2 eur."
#   - "Pogoj za uporabo strelišča je veljavna orožna listina ter posest lastnega orožja."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/sdrojal

  - title: envelope
    url: mailto:sd@rojal.si

  - title: map-marker
    url: https://g.page/sdrojal?share

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: compact # possible values: nested expanded compact compressed
